development:
  forest_env_secret: 3dc3ed7646be58e9a03a32de9b4b55e8f22a2cbcc75b25529e85d69a48cede9e
  forest_auth_secret: LUS9CB62U-kHKBA-qyB5Kw
  forest_application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
